package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private int idpersona;
     private Persona persona;
     private String licencia;
     private Date fechaExpiracion;
     private Set papeletaMultas = new HashSet(0);

    public Conductor() {
    }

	
    public Conductor(Persona persona) {
        this.persona = persona;
    }
    public Conductor(Persona persona, String licencia, Date fechaExpiracion, Set papeletaMultas) {
       this.persona = persona;
       this.licencia = licencia;
       this.fechaExpiracion = fechaExpiracion;
       this.papeletaMultas = papeletaMultas;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


