package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * MarcaVehiculo generated by hbm2java
 */
public class MarcaVehiculo  implements java.io.Serializable {


     private Integer idmarca;
     private String descripcion;
     private String pais;
     private Set vehiculos = new HashSet(0);

    public MarcaVehiculo() {
    }

    public MarcaVehiculo(String descripcion, String pais, Set vehiculos) {
       this.descripcion = descripcion;
       this.pais = pais;
       this.vehiculos = vehiculos;
    }
   
    public Integer getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(Integer idmarca) {
        this.idmarca = idmarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


