package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ModeloVehiculo generated by hbm2java
 */
public class ModeloVehiculo  implements java.io.Serializable {


     private Integer idmodelo;
     private String descripcion;
     private Set vehiculos = new HashSet(0);

    public ModeloVehiculo() {
    }

    public ModeloVehiculo(String descripcion, Set vehiculos) {
       this.descripcion = descripcion;
       this.vehiculos = vehiculos;
    }
   
    public Integer getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(Integer idmodelo) {
        this.idmodelo = idmodelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


