package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Policia generated by hbm2java
 */
public class Policia  implements java.io.Serializable {


     private int idpersona;
     private Persona persona;
     private String grado;
     private Integer numPlaca;
     private Set papeletaMultas = new HashSet(0);

    public Policia() {
    }

	
    public Policia(Persona persona) {
        this.persona = persona;
    }
    public Policia(Persona persona, String grado, Integer numPlaca, Set papeletaMultas) {
       this.persona = persona;
       this.grado = grado;
       this.numPlaca = numPlaca;
       this.papeletaMultas = papeletaMultas;
    }
   
    public int getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(int idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public Integer getNumPlaca() {
        return this.numPlaca;
    }
    
    public void setNumPlaca(Integer numPlaca) {
        this.numPlaca = numPlaca;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


