package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoInfraccion generated by hbm2java
 */
public class TipoInfraccion  implements java.io.Serializable {


     private Integer idtipo;
     private String descripcion;
     private Integer importe;
     private Set papeletaMultas = new HashSet(0);

    public TipoInfraccion() {
    }

    public TipoInfraccion(String descripcion, Integer importe, Set papeletaMultas) {
       this.descripcion = descripcion;
       this.importe = importe;
       this.papeletaMultas = papeletaMultas;
    }
   
    public Integer getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(Integer idtipo) {
        this.idtipo = idtipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getImporte() {
        return this.importe;
    }
    
    public void setImporte(Integer importe) {
        this.importe = importe;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


