package multas.entity;
// Generated 10-feb-2020 1:27:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private Integer idvehiculo;
     private MarcaVehiculo marcaVehiculo;
     private ModeloVehiculo modeloVehiculo;
     private Persona persona;
     private Integer anio;
     private String color;
     private Set papeletaMultas = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(MarcaVehiculo marcaVehiculo, ModeloVehiculo modeloVehiculo, Persona persona) {
        this.marcaVehiculo = marcaVehiculo;
        this.modeloVehiculo = modeloVehiculo;
        this.persona = persona;
    }
    public Vehiculo(MarcaVehiculo marcaVehiculo, ModeloVehiculo modeloVehiculo, Persona persona, Integer anio, String color, Set papeletaMultas) {
       this.marcaVehiculo = marcaVehiculo;
       this.modeloVehiculo = modeloVehiculo;
       this.persona = persona;
       this.anio = anio;
       this.color = color;
       this.papeletaMultas = papeletaMultas;
    }
   
    public Integer getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(Integer idvehiculo) {
        this.idvehiculo = idvehiculo;
    }
    public MarcaVehiculo getMarcaVehiculo() {
        return this.marcaVehiculo;
    }
    
    public void setMarcaVehiculo(MarcaVehiculo marcaVehiculo) {
        this.marcaVehiculo = marcaVehiculo;
    }
    public ModeloVehiculo getModeloVehiculo() {
        return this.modeloVehiculo;
    }
    
    public void setModeloVehiculo(ModeloVehiculo modeloVehiculo) {
        this.modeloVehiculo = modeloVehiculo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Integer getAnio() {
        return this.anio;
    }
    
    public void setAnio(Integer anio) {
        this.anio = anio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


