package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conductor generated by hbm2java
 */
public class Conductor  implements java.io.Serializable {


     private BigDecimal idpersona;
     private Persona persona;
     private String licencia;
     private Date fechaexpiracion;
     private Set papeletaMultas = new HashSet(0);

    public Conductor() {
    }

	
    public Conductor(Persona persona) {
        this.persona = persona;
    }
    public Conductor(Persona persona, String licencia, Date fechaexpiracion, Set papeletaMultas) {
       this.persona = persona;
       this.licencia = licencia;
       this.fechaexpiracion = fechaexpiracion;
       this.papeletaMultas = papeletaMultas;
    }
   
    public BigDecimal getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getLicencia() {
        return this.licencia;
    }
    
    public void setLicencia(String licencia) {
        this.licencia = licencia;
    }
    public Date getFechaexpiracion() {
        return this.fechaexpiracion;
    }
    
    public void setFechaexpiracion(Date fechaexpiracion) {
        this.fechaexpiracion = fechaexpiracion;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


