package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Marca generated by hbm2java
 */
public class Marca  implements java.io.Serializable {


     private BigDecimal idmarca;
     private String descripcion;
     private String pais;
     private Set vehiculos = new HashSet(0);

    public Marca() {
    }

	
    public Marca(BigDecimal idmarca) {
        this.idmarca = idmarca;
    }
    public Marca(BigDecimal idmarca, String descripcion, String pais, Set vehiculos) {
       this.idmarca = idmarca;
       this.descripcion = descripcion;
       this.pais = pais;
       this.vehiculos = vehiculos;
    }
   
    public BigDecimal getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(BigDecimal idmarca) {
        this.idmarca = idmarca;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


