package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Modelo generated by hbm2java
 */
public class Modelo  implements java.io.Serializable {


     private BigDecimal idmodelo;
     private String descripcion;
     private Set vehiculos = new HashSet(0);

    public Modelo() {
    }

	
    public Modelo(BigDecimal idmodelo) {
        this.idmodelo = idmodelo;
    }
    public Modelo(BigDecimal idmodelo, String descripcion, Set vehiculos) {
       this.idmodelo = idmodelo;
       this.descripcion = descripcion;
       this.vehiculos = vehiculos;
    }
   
    public BigDecimal getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(BigDecimal idmodelo) {
        this.idmodelo = idmodelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }




}


