package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PapeletaMulta generated by hbm2java
 */
public class PapeletaMulta  implements java.io.Serializable {


     private BigDecimal idpapeleta;
     private TipoInfraccion tipoInfraccion;
     private Conductor conductor;
     private Policia policia;
     private Vehiculo vehiculo;
     private Date fecha;

    public PapeletaMulta() {
    }

	
    public PapeletaMulta(BigDecimal idpapeleta, TipoInfraccion tipoInfraccion, Conductor conductor, Policia policia, Vehiculo vehiculo) {
        this.idpapeleta = idpapeleta;
        this.tipoInfraccion = tipoInfraccion;
        this.conductor = conductor;
        this.policia = policia;
        this.vehiculo = vehiculo;
    }
    public PapeletaMulta(BigDecimal idpapeleta, TipoInfraccion tipoInfraccion, Conductor conductor, Policia policia, Vehiculo vehiculo, Date fecha) {
       this.idpapeleta = idpapeleta;
       this.tipoInfraccion = tipoInfraccion;
       this.conductor = conductor;
       this.policia = policia;
       this.vehiculo = vehiculo;
       this.fecha = fecha;
    }
   
    public BigDecimal getIdpapeleta() {
        return this.idpapeleta;
    }
    
    public void setIdpapeleta(BigDecimal idpapeleta) {
        this.idpapeleta = idpapeleta;
    }
    public TipoInfraccion getTipoInfraccion() {
        return this.tipoInfraccion;
    }
    
    public void setTipoInfraccion(TipoInfraccion tipoInfraccion) {
        this.tipoInfraccion = tipoInfraccion;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }
    public Policia getPolicia() {
        return this.policia;
    }
    
    public void setPolicia(Policia policia) {
        this.policia = policia;
    }
    public Vehiculo getVehiculo() {
        return this.vehiculo;
    }
    
    public void setVehiculo(Vehiculo vehiculo) {
        this.vehiculo = vehiculo;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


