package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private BigDecimal idpersona;
     private String nombre;
     private String direccion;
     private Date fechanacimiento;
     private Set vehiculos = new HashSet(0);
     private Policia policia;
     private Conductor conductor;

    public Persona() {
    }

	
    public Persona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }
    public Persona(BigDecimal idpersona, String nombre, String direccion, Date fechanacimiento, Set vehiculos, Policia policia, Conductor conductor) {
       this.idpersona = idpersona;
       this.nombre = nombre;
       this.direccion = direccion;
       this.fechanacimiento = fechanacimiento;
       this.vehiculos = vehiculos;
       this.policia = policia;
       this.conductor = conductor;
    }
   
    public BigDecimal getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public Set getVehiculos() {
        return this.vehiculos;
    }
    
    public void setVehiculos(Set vehiculos) {
        this.vehiculos = vehiculos;
    }
    public Policia getPolicia() {
        return this.policia;
    }
    
    public void setPolicia(Policia policia) {
        this.policia = policia;
    }
    public Conductor getConductor() {
        return this.conductor;
    }
    
    public void setConductor(Conductor conductor) {
        this.conductor = conductor;
    }




}


