package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Policia generated by hbm2java
 */
public class Policia  implements java.io.Serializable {


     private BigDecimal idpersona;
     private Persona persona;
     private String grado;
     private BigDecimal NPlaca;
     private Set papeletaMultas = new HashSet(0);

    public Policia() {
    }

	
    public Policia(Persona persona, BigDecimal NPlaca) {
        this.persona = persona;
        this.NPlaca = NPlaca;
    }
    public Policia(Persona persona, String grado, BigDecimal NPlaca, Set papeletaMultas) {
       this.persona = persona;
       this.grado = grado;
       this.NPlaca = NPlaca;
       this.papeletaMultas = papeletaMultas;
    }
   
    public BigDecimal getIdpersona() {
        return this.idpersona;
    }
    
    public void setIdpersona(BigDecimal idpersona) {
        this.idpersona = idpersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getGrado() {
        return this.grado;
    }
    
    public void setGrado(String grado) {
        this.grado = grado;
    }
    public BigDecimal getNPlaca() {
        return this.NPlaca;
    }
    
    public void setNPlaca(BigDecimal NPlaca) {
        this.NPlaca = NPlaca;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


