package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * TipoInfraccion generated by hbm2java
 */
public class TipoInfraccion  implements java.io.Serializable {


     private BigDecimal idtipo;
     private String descripcion;
     private BigDecimal importe;
     private Set papeletaMultas = new HashSet(0);

    public TipoInfraccion() {
    }

	
    public TipoInfraccion(BigDecimal idtipo) {
        this.idtipo = idtipo;
    }
    public TipoInfraccion(BigDecimal idtipo, String descripcion, BigDecimal importe, Set papeletaMultas) {
       this.idtipo = idtipo;
       this.descripcion = descripcion;
       this.importe = importe;
       this.papeletaMultas = papeletaMultas;
    }
   
    public BigDecimal getIdtipo() {
        return this.idtipo;
    }
    
    public void setIdtipo(BigDecimal idtipo) {
        this.idtipo = idtipo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getImporte() {
        return this.importe;
    }
    
    public void setImporte(BigDecimal importe) {
        this.importe = importe;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


