package multas.entity;
// Generated 10-feb-2020 22:40:43 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Vehiculo generated by hbm2java
 */
public class Vehiculo  implements java.io.Serializable {


     private BigDecimal idvehiculo;
     private Persona persona;
     private Marca marca;
     private Modelo modelo;
     private BigDecimal anio;
     private String color;
     private Set papeletaMultas = new HashSet(0);

    public Vehiculo() {
    }

	
    public Vehiculo(BigDecimal idvehiculo, Persona persona, Marca marca, Modelo modelo) {
        this.idvehiculo = idvehiculo;
        this.persona = persona;
        this.marca = marca;
        this.modelo = modelo;
    }
    public Vehiculo(BigDecimal idvehiculo, Persona persona, Marca marca, Modelo modelo, BigDecimal anio, String color, Set papeletaMultas) {
       this.idvehiculo = idvehiculo;
       this.persona = persona;
       this.marca = marca;
       this.modelo = modelo;
       this.anio = anio;
       this.color = color;
       this.papeletaMultas = papeletaMultas;
    }
   
    public BigDecimal getIdvehiculo() {
        return this.idvehiculo;
    }
    
    public void setIdvehiculo(BigDecimal idvehiculo) {
        this.idvehiculo = idvehiculo;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Marca getMarca() {
        return this.marca;
    }
    
    public void setMarca(Marca marca) {
        this.marca = marca;
    }
    public Modelo getModelo() {
        return this.modelo;
    }
    
    public void setModelo(Modelo modelo) {
        this.modelo = modelo;
    }
    public BigDecimal getAnio() {
        return this.anio;
    }
    
    public void setAnio(BigDecimal anio) {
        this.anio = anio;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public Set getPapeletaMultas() {
        return this.papeletaMultas;
    }
    
    public void setPapeletaMultas(Set papeletaMultas) {
        this.papeletaMultas = papeletaMultas;
    }




}


